# Credit:
# https://github.com/AlexNijjar/Mod-Template/blob/main/src/main/resources/fileTemplates/j2ee/release.yml.ft
# https://github.com/FabricMC/fabric-example-mod/blob/1.21/.github/workflows/build.yml

name: release
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: get version
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./gradle.properties"
          properties: "mod_version minecraft_version"

      - name: upload
        id: fabric_release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/!(*-@(dev|sources|dev-shadow)).jar
          name: "Xungeon Timer ${{ steps.properties.outputs.mod_version }}"
          version: ${{ steps.properties.outputs.mod_version }}
          version-type: release
          changelog-file: changelog.md
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.minecraft_version }}
          version-resolver: exact

          dependencies: |
            fabric-api | depends | *
            owo-lib | depends | *
            modmenu | suggests | *